### ISSUE TITLE
Deformable LKA module

### ISSUE THREAD

**Issue by Ystartff** [xmindflow/deformableLKA#1]
Hello, I would like to know where the complete code flow of the Deformable LKA module in Figure 2 in your paper is, but I didn't find it

**Comment by amirhossein-kz** [comment]
Hi @Ystartff ,

Thank you for your interest. You can find it here:

https://github.com/xmindflow/deformableLKA/blob/68c87dfa9d1cd4cd935ce9fc6ef37c262de6fd53/2D/deformable_LKA/deformable_LKA.py#L124
