### ISSUE TITLE
maxvit_rmlp_small_rw_224_sw-6ef0ae4f.pth

### ISSUE THREAD

**Issue by MoonLooking** [xmindflow/deformableLKA#10]
Hello, while I was training the model, the system reminded me that it couldn't find the file “maxvit_rmlp_small_rw_224_sw-6ef0ae4f.pth”. How can I solve it? thanks  ( :

**Comment by Leonngm** [comment]
Hi, 
thanks for the interest in our code. We got the pre-trained MaxViT backbone from the [Merit Group](https://github.com/SLDGroup/MERIT) their pretrained model is located here: [MaxVit pretrain](https://drive.google.com/drive/folders/1k-s75ZosvpRGZEWl9UEpc_mniK3nL2xq?usp=share_link).
Place the downloaded model in the correct path.
I hope this resolves the issue. 
Best regards

**Comment by MoonLooking** [comment]
Thanks for your help！:)

**Comment by j9ndv6k4zw-sys** [comment]
This folder is empty. If possible, could you send me a copy? My email is yjh200103@163.com
