### ISSUE TITLE
Regarding the reproduction of ISIC2017 and ISIC2018

### ISSUE THREAD

**Issue by sui1999** [xmindflow/deformableLKA#12]
Hello author, while reproducing ISIC2018 and ISIC2018, I found a significant difference between the final results and those in your paper. May I ask if you have done any processing on the dataset, or could you upload the dataset you have processed.

**Comment by Leonngm** [comment]
Hi, 
thanks for the interest in our code. For the skin datasets, we preprocess the data with this script for ISIC2017 [preprocess](https://github.com/xmindflow/deformableLKA/blob/main/2D/skin_code/Prepare_ISIC2017.py). Other preprocessing is not done.
