### ISSUE TITLE
The results of "mean_dice" and "mean_hd95" 

### ISSUE THREAD

**Issue by XyFightingXy** [xmindflow/deformableLKA#15]
Dear author, while I was training the model designed by myself, "mean_dice" and "mean_hd95" will arise zero values. How can I solve it? Thanks.

![error](https://github.com/xmindflow/deformableLKA/assets/162257937/747b7619-db4b-4eec-9dcc-36b07ece7904)

**Comment by Leonngm** [comment]
Hi,
thanks for the interest in our code. Which model did you try to train? Which training parameters did you used?
Without further information it is hard to solve your issue.
Best, 
Leon
