### ISSUE TITLE
can not find the file

### ISSUE THREAD

**Issue by xiexuxiang** [xmindflow/deformableLKA#16]
Dear author：
When I run train_MaxViT_deform_LKA.py
the result：FileNotFoundError: [Errno 2] No such file or directory: './pretrained_pth/maxvit/maxvit_rmlp_small_rw_224_sw-6ef0ae4f.pth'

**Comment by Banquettt6** [comment]
did you solve it? I've got the same error

**Comment by lepotatoguy** [comment]
> did you solve it? I've got the same error

Hello @Banquettt6 
I solved it in this way, updated in the documentation. https://github.com/lepotatoguy/deformableLKA/blob/main/2D/README.md
I hope this helps. 

Thanks.
