### ISSUE TITLE
can not find best_model.pth and best_model.pth.txt

### ISSUE THREAD

**Issue by xiexuxiang** [xmindflow/deformableLKA#17]
Dear author：
Due to the poor performance of my computer, it is difficult to finish running the train_MaxViT_deform_LKA.py file.
When I run the test.py file it shows that I don't have best_model.pth and best_model.pth.txt
Do I need to run train_MaxViT_deform_LKA.py completely to obtain these two files? Or can these two files be downloaded directly?

**Comment by Leonngm** [comment]
Hi,
to run the test file, you need the trained checkpoint. It is provided under this [link](https://drive.google.com/drive/folders/1TY7G0X32kGbgnzx_Zn5px0gW8fVF4ptI?usp=sharing). You can rename it accordingly. A .txt file should not be necessary.
Best
Leon
