### ISSUE TITLE
Cannot find the pre-trained weight file

### ISSUE THREAD

**Issue by Candice-Y** [xmindflow/deformableLKA#18]
Hello, your work is excellent, and I'm eager to delve deeper into learning. However, I encountered an issue while running the training code, which indicates that the pre-training weight file is missing. 

As shown below: 
`FileNotFoundError: [Errno 2] No such file or directory: './pretrained_pth/maxvit/maxvit_rmlp_small_rw_224_sw-6ef0ae4f.pth'`

I couldn't find this particular pre-training weight file on the code homepage. Would you mind providing it? If possible, here's my email: allure0719@163.com.

**Comment by Leonngm** [comment]
Hi, 
thanks for the interest in our work. In #10 it is mentioned where you can download the pre-trained weights.
Best

**Comment by Candice-Y** [comment]
> Hi, thanks for the interest in our work. In #10 it is mentioned where you can download the pre-trained weights. Best

ok, I find it. thanks very much~
