### ISSUE TITLE
OSError: [Errno 22] Invalid argument

### ISSUE THREAD

**Issue by XyFightingXy** [xmindflow/deformableLKA#19]
Dear author：When I run the train_MaxViT_deform_LKA.py file, it shows OSError: [Errno 22] Invalid argument: '.\\model_out\\MaxViT_improved_deform_LKA_two_layer\\MaxViT_improved_deform_LKA_2024-03-16 12:43:30.810350dice.png'. How can I solve it?

![微信截图_20240316170856](https://github.com/xmindflow/deformableLKA/assets/162257937/69c69e9e-d422-433e-b20c-1a55b591ff22)

**Comment by Leonngm** [comment]
Hi,
again, it is impossible to say without seeing your modifications. In the vanilla repository, no .png files are saved or loaded.
