### ISSUE TITLE
How to make the Qualitative results into the pics like in your paper?

### ISSUE THREAD

**Issue by WuJuli** [xmindflow/deformableLKA#21]
Dear author, may I ask if you can tell us how to obtain such visual results after obtaining the predicted results? Is it through any software?
![d59c346f67408ce538ff19562a90951](https://github.com/xmindflow/deformableLKA/assets/46019998/ddc76e56-d0ba-44f9-991f-61154c7b9a9d)
![e4d52254f23282b00d42688756ff496](https://github.com/xmindflow/deformableLKA/assets/46019998/8729a3d8-e63a-4ae2-8edc-034cfc9d3e85)
![086ca8b528d94b56998f2ed5583504a](https://github.com/xmindflow/deformableLKA/assets/46019998/04d874f3-814a-438b-9d3c-c56dc0e274e2)
Thank you very much! Thank you for your generous sharing!

**Comment by Leonngm** [comment]
Hi,
the visualizations are done with the software [3D Slicer](https://www.slicer.org/). You can load the volumes as segmentations and adjust the colors. 
Best regards!
