### ISSUE TITLE
i cant visit 3d synpase dataset

### ISSUE THREAD

**Issue by zyqzyqhappiness** [xmindflow/deformableLKA#22]
because i dont have an identification of the  from identity provider 'live.com' does not exist in tenant 'Mohamed Bin Zayed University of Artificial Intelligence' and cannot access the application '00000003-0000-0ff1-ce00-000000000000'(Office 365 SharePoint Online) in that tenant. The account needs to be added as an external user in the tenant first. Sign out and sign in again with a different Azure Active Directory user account. can you change the source? thank u!

**Comment by Leonngm** [comment]
Hi,
the dataset is not provided by us. Please request it from the official source, if it is not available at your location.
Best
