### ISSUE TITLE
There is no way to find the key code for variable convolution in that part.

### ISSUE THREAD

**Issue by liaochuanlin** [xmindflow/deformableLKA#5]

**Comment by Leonngm** [comment]
For 3D deformable convolution, we use the implementation of [D3Dnet](https://github.com/XinyiYing/D3Dnet). The source code is located in this [folder](https://github.com/xmindflow/deformableLKA/tree/main/3D/dcn).

Follow the [3D Readme](https://github.com/xmindflow/deformableLKA/tree/main/3D#readme) for installation instructions.
