### ISSUE TITLE
 ERROR: Failed building wheel for D3D

### ISSUE THREAD

**Issue by liaochuanlin** [xmindflow/deformableLKA#7]
note: This error originates from a subprocess, and is likely not a problem with pip.
  ERROR: Failed building wheel for D3D
ERROR: Could not build wheels for D3D, which is required to install pyproject.toml-based projects

**Comment by Leonngm** [comment]
What version of CUDA, Pytorch and Python are you using?
The code is tested with CUDA 11.3, Pytorch 1.11 and Pytohn 3.8. Please set up your environment as specified in the [Readme](https://github.com/xmindflow/deformableLKA/blob/main/3D/README.md)
