### ISSUE TITLE
Pancreas code loading state_dict for D_LKA_Net error

### ISSUE THREAD

**Issue by ai1808328** [xmindflow/deformableLKA#8]
I followed all the steps you have including downloading the same Python and PyTorch versions for running the pancreas code.

The train_pancreas.py ran well and the weights were saved as intended. However, I am getting an error when running the test_pancreas.py and I cannot seem to fix it.

![image (1)](https://github.com/xmindflow/deformableLKA/assets/101464359/3d456ee5-fa75-4ee6-a586-7b17f4c0c1d5)
![image (2)](https://github.com/xmindflow/deformableLKA/assets/101464359/f6bf8340-5e7d-43bb-9bd2-c32d2d496b54)

**Comment by Leonngm** [comment]
Hi,
thanks for your interest in our code.

Could you share the create model function of the train_pancreas.py script and the create model function for your test_pancreas.py script?

**Comment by Leonngm** [comment]
I think I got your error: 

In _test_pancreas.py_ please replace 
`net = D_LKA_Net(in_channels=1, 
                           out_channels=num_classes, 
                           img_size=[96, 96, 96],
                           patch_size=(2,2,2),
                           input_size=[48*48*48, 24*24*24,12*12*12,6*6*6],
                           trans_block=Transformerblock,
                           do_ds=False)`

with: 
`net = D_LKA_Net(in_channels=1, 
                           out_channels=num_classes, 
                           img_size=[96, 96, 96],
                           patch_size=(2,2,2),
                           input_size=[48*48*48, 24*24*24,12*12*12,6*6*6],
                           trans_block=TransformerBlock_3D_single_deform_LKA,
                           do_ds=False)`

**Comment by ai1808328** [comment]
Thank you!

**Comment by ai1808328** [comment]
Thank you!
