### ISSUE TITLE
Problem encountered during reproduction

### ISSUE THREAD

**Issue by yangz9527** [xmindflow/deformableLKA#9]
Hello author, I noticed a strange phenomenon while reproducing the results of DAEFormer on the ISIC2018 dataset. After starting training on the preprocessed dataset, I noticed a gradient explosion in the loss value section. May I ask if this is caused by some issues with the code of the processed dataset
![5eaf3fa7038d7c9b93bd80146179c78](https://github.com/xmindflow/deformableLKA/assets/118180487/f3cfc148-cf8c-4ba6-93e1-9212b1ab07a6)
![a6dbd2a6b0df1868f1c716150a08810](https://github.com/xmindflow/deformableLKA/assets/118180487/df97b198-6ae4-49d1-95f5-0777e368d0da)

**Comment by Leonngm** [comment]
Hi, 
thanks for the interest in our code.
The results for the DAEFormer were copied from the DAEFormer publication and not reproduced for this work. Please check if you preprocessed the data with the preprocessing script. Since the loss is already nan after the first iteration, it could also be a different problem.

**Comment by yangz9527** [comment]
> Hi, thanks for the interest in our code. The results for the DAEFormer were copied from the DAEFormer publication and not reproduced for this work. Please check if you preprocessed the data with the preprocessing script. Since the loss is already nan after the first iteration, it could also be a different problem.

Thank you for taking the time to read and reply to my comments. In fact, I am currently reproducing the results of your previous research on the skin disease ISIC2018 dataset in the DAEformer paper. If possible, could you please update the training and testing codes for the skin disease dataset in the DAEformer? This is very important to me. Thank you very much

**Comment by Leonngm** [comment]
To train the DAEFormer model on the skin dataset, replace the model in [this line](https://github.com/xmindflow/deformableLKA/blob/main/2D/skin_code/train_skinLKA2017.py#L103) with the DAEFormer model.
